on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/aws-glue.yml'


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - name: Install aws cli
          id: install-aws-cli
          uses: unfor19/install-aws-cli-action@v1
          with:
            version: 2
            verbose: false
            arch: amd64
            rootdir: ""
            workdir: "" 

        - name: Set AWS credentials
          run: export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} && export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} && export AWS_DEFAULT_REGION=us-east-1

        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            submodules: 'true'

        - name: Upload files to S3
          run: aws s3 cp unzip_glue_job.py s3://tini-d-gluebucket-001/py_scripts/ --region us-east-1 --debug
        
        #- name: Create AWS Glue Job
         # run: aws glue create-job --name unzip_glue_job.py --role tini-d-glue-crawler-role-001 --command Name=glueetl,ScriptLocation=s3://tini-d-gluebucket-001/py_scripts/unzip_glue_job.py  --region us-east-1 --debug
    
        #- name: Update AWS Glue Job
         # run: aws glue update-job --job-name unzip_glue_job.py --job-update #"Role=tini-d-glue-crawler-role-001,Command={Name=glueetl,ScriptLocation=s3://tini-d-gluebucket-001/py_scripts/unzip_glue_job.py}" --region us-east-1 --debug      
        
        - name: Update AWS Glue Job
          run:  aws glue update-job --job-name unzip_glue_job.py --job-update
                "Role="tini-d-glue-crawler-role-001","Command"={"Name"="glueetl","ScriptLocation"="s3://tini-d-gluebucket-001/py_scripts/unzip_glue_job.py"},"MaxRetries"= 0,"Timeout"=2880,"WorkerType"="G.1X","NumberOfWorkers"=2,"GlueVersion"="1.0"" --region us-east-1 --debug

        #- name: Run AWS Glue Job
         # run: aws glue start-job-run --job-name unzip_glue_job.py  --region us-east-1 --debug 

    
 

